name: Format
on:
    pull_request:
        types:
            - opened
            - reopened
            - synchronize
    push:
        branches:
            - release
            - release-candidate
jobs:
    job:
        name: Format
        runs-on: ubuntu-latest
        steps:
            - name: GitHub Checkout
              uses: actions/checkout@v4
              with:
                persist-credentials: false
                submodules: recursive
                token: ${{ secrets.GITHUB_TOKEN }}
            - name: Install Rust Toolchain
              uses: actions-rust-lang/setup-rust-toolchain@v1
              with:
                components: rustfmt
                toolchain: nightly
            - name: Set-Up Cache
              uses: Swatinem/rust-cache@v2
            - name: Cargo FMT
              uses: actions-rust-lang/rustfmt@v1
