name: Lint
on:
    pull_request:
        types:
            - opened
            - reopened
            - synchronize
    push:
        branches:
            - release
            - release-candidate
jobs:
    job:
        name: Lint
        runs-on: ubuntu-latest
        steps:
            - name: GitHub Checkout
              uses: actions/checkout@v4
              with:
                persist-credentials: false
                submodules: recursive
                token: ${{ secrets.GITHUB_TOKEN }}
            - name: Install Rust Toolchain
              uses: actions-rust-lang/setup-rust-toolchain@v1
              with:
                components: clippy
                toolchain: nightly
            - name: Set-Up Cache
              uses: Swatinem/rust-cache@v2
            - name: Cargo Clippy
              uses: giraffate/clippy-action@v1
              with:
                reporter: 'github-pr-review'
                github_token: ${{ secrets.GITHUB_TOKEN }}
