name: Release
on:
    push:
        branches:
            - release
            - release-candidate
jobs:
    job:
        name: Release
        permissions:
            contents: write
        runs-on: ubuntu-latest
        steps:
            - name: GitHub Checkout
              uses: actions/checkout@v4
              with:
                fetch-depth: 0
                persist-credentials: false
                submodules: recursive
                token: ${{ secrets.AM_GITHUB_TOKEN }}
            - name: Install Rust Toolchain
              uses: actions-rust-lang/setup-rust-toolchain@v1
              with:
                toolchain: nightly
            - name: Set-Up Cache
              uses: Swatinem/rust-cache@v2
            - name: Install `semantic-release-rust`
              uses: baptiste0928/cargo-install@v3
              with:
                crate: semantic-release-rust
                version: '1.0.0-alpha.8'
            - name: Release Changes
              env:
                CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}
                GIT_AUTHOR_EMAIL: 'am@scream.com'
                GIT_AUTHOR_NAME: 'AM'
                GIT_COMMITTER_EMAIL: 'am@scream.com'
                GIT_COMMITTER_NAME: 'AM'
                GITHUB_TOKEN: ${{ secrets.AM_GITHUB_TOKEN }}
              uses: cycjimmy/semantic-release-action@v4.0.0
              with:
                extra_plugins: |
                    @saithodev/semantic-release-backmerge@4.0.1
                    @semantic-release/changelog@6.0.3
                    @semantic-release/commit-analyzer@12.0.0
                    @semantic-release/exec@6.0.3
                    @semantic-release/git@10.0.1
                    @semantic-release/release-notes-generator@13.0.0
                    conventional-changelog-conventionalcommits@5.0.0
                semantic_version: 23.1.1
